// //10-Days-Project\backend\src\tarotCards.js

const tarotCards = {
      
}
// const tarotCards = {
//       "The Fool": "Represents new beginnings, innocence, and spontaneity.",
//       "The Magician": "Symbolizes manifestation, resourcefulness, and power.",
//       "The High Priestess": "Represents intuition, mystery, and wisdom.",
//       "The Empress": "Represents fertility, abundance, and nurturing.",
//       "The Emperor": "Symbolizes authority, stability, and leadership.",
//       "The Hierophant": "Represents tradition, wisdom, and spiritual guidance.",
//       "The Lovers": "Represents love, harmony, and partnership.",
//       "The Chariot": "Represents willpower, determination, and victory.",
//       "Strength": "Symbolizes courage, inner strength, and patience.",
//       "The Hermit": "Represents introspection, solitude, and wisdom.",
//       "Wheel of Fortune": "Symbolizes cycles, destiny, and luck.",
//       "Justice": "Represents fairness, balance, and truth.",
//       "The Hanged Man": "Represents suspension, new perspectives, and sacrifice.",
//       "Death": "Symbolizes transformation, endings, and new beginnings.",
//       "Temperance": "Represents balance, moderation, and harmony.",
//       "The Devil": "Represents temptation, materialism, and bondage.",
//       "The Tower": "Represents destruction, revelation, and sudden change.",
//       "The Star": "Represents hope, inspiration, and spiritual guidance.",
//       "The Moon": "Symbolizes illusion, intuition, and the subconscious.",
//       "The Sun": "Represents joy, success, and vitality.",
//       "Judgement": "Represents reflection, judgment, and renewal.",
//       "The World": "Symbolizes completion, wholeness, and accomplishment.",
    
//       // Minor Arcana - Cups
//       "Ace of Cups": "Represents new emotional beginnings and love.",
//       "Two of Cups": "Represents partnerships, mutual attraction, and love.",
//       "Three of Cups": "Symbolizes celebration, friendship, and joy.",
//       "Four of Cups": "Represents contemplation, apathy, and reevaluation.",
//       "Five of Cups": "Represents loss, regret, and focusing on the negative.",
//       "Six of Cups": "Symbolizes nostalgia, memories, and childhood.",
//       "Seven of Cups": "Represents choices, illusions, and temptation.",
//       "Eight of Cups": "Represents leaving something behind, emotional withdrawal.",
//       "Nine of Cups": "Symbolizes contentment, satisfaction, and wish fulfillment.",
//       "Ten of Cups": "Represents happiness, harmony, and emotional fulfillment.",
//       "Page of Cups": "Symbolizes creativity, intuition, and a new emotional journey.",
//       "Knight of Cups": "Represents romance, charm, and idealism.",
//       "Queen of Cups": "Represents compassion, emotional balance, and nurturing.",
//       "King of Cups": "Symbolizes emotional control, wisdom, and maturity.",
    
//       // Minor Arcana - Pentacles
//       "Ace of Pentacles": "Represents new beginnings, prosperity, and material success.",
//       "Two of Pentacles": "Represents balance, adaptability, and juggling multiple tasks.",
//       "Three of Pentacles": "Represents collaboration, skill-building, and teamwork.",
//       "Four of Pentacles": "Symbolizes security, stability, and possessiveness.",
//       "Five of Pentacles": "Represents hardship, poverty, and financial struggle.",
//       "Six of Pentacles": "Symbolizes generosity, charity, and balance in giving and receiving.",
//       "Seven of Pentacles": "Represents patience, assessment, and long-term goals.",
//       "Eight of Pentacles": "Symbolizes diligence, hard work, and mastery of a craft.",
//       "Nine of Pentacles": "Represents independence, luxury, and financial abundance.",
//       "Ten of Pentacles": "Symbolizes wealth, family, and legacy.",
//       "Page of Pentacles": "Represents ambition, study, and new material opportunities.",
//       "Knight of Pentacles": "Symbolizes responsibility, hard work, and dedication.",
//       "Queen of Pentacles": "Represents nurturing, practicality, and financial security.",
//       "King of Pentacles": "Symbolizes wealth, success, and business leadership.",
    
//       // Minor Arcana - Swords
//       "Ace of Swords": "Represents new ideas, clarity, and breakthroughs.",
//       "Two of Swords": "Symbolizes decision-making, choices, and indecision.",
//       "Three of Swords": "Represents heartbreak, emotional pain, and sorrow.",
//       "Four of Swords": "Symbolizes rest, recovery, and contemplation.",
//       "Five of Swords": "Represents conflict, competition, and victory at a cost.",
//       "Six of Swords": "Symbolizes transition, moving forward, and healing.",
//       "Seven of Swords": "Represents deceit, strategy, and self-interest.",
//       "Eight of Swords": "Symbolizes restriction, mental entrapment, and self-imposed limitations.",
//       "Nine of Swords": "Represents anxiety, fear, and sleepless nights.",
//       "Ten of Swords": "Symbolizes betrayal, painful endings, and rock bottom.",
//       "Page of Swords": "Represents curiosity, intellect, and a new mental journey.",
//       "Knight of Swords": "Symbolizes action, quick thinking, and impulsiveness.",
//       "Queen of Swords": "Represents clear thinking, independence, and truth.",
//       "King of Swords": "Symbolizes intellectual authority, logic, and strategic thinking.",
    
//       // Minor Arcana - Wands
//       "Ace of Wands": "Represents inspiration, new opportunities, and action.",
//       "Two of Wands": "Symbolizes planning, future vision, and potential.",
//       "Three of Wands": "Represents expansion, growth, and foresight.",
//       "Four of Wands": "Symbolizes celebration, homecoming, and stability.",
//       "Five of Wands": "Represents competition, conflict, and challenges.",
//       "Six of Wands": "Symbolizes victory, success, and recognition.",
//       "Seven of Wands": "Represents defense, courage, and standing your ground.",
//       "Eight of Wands": "Symbolizes speed, action, and progress.",
//       "Nine of Wands": "Represents perseverance, resilience, and the last stretch.",
//       "Ten of Wands": "Symbolizes burden, responsibility, and being overwhelmed.",
//       "Page of Wands": "Represents enthusiasm, adventure, and inspiration.",
//       "Knight of Wands": "Symbolizes energy, passion, and impulsiveness.",
//       "Queen of Wands": "Represents confidence, creativity, and leadership.",
//       "King of Wands": "Symbolizes leadership, vision, and taking action."
// };
    
module.exports = { tarotCards };